INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Bahrain', '02 Mar 2024', 'Verstappen', 9, 57);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Saudi Arabia', '09 Mar 2024', 'Verstappen', 9, 50);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Australia', '24 Mar 2024', 'Sainz', 3, 58);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Japan', '07 Apr 2024', 'Verstappen', 9, 53);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('China', '21 Apr 2024', 'Verstappen', 9, 56);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Miami', '05 May 2024', 'Norris', 6, 57);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Emilia-Romagna', '19 May 2024', 'Verstappen', 9, 63);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Monaco', '26 May 2024', 'Leclerc', 3, 78);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Canada', '09 Jun 2024', 'Verstappen', 9, 70);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Spain', '23 Jun 2024', 'Verstappen', 9, 66);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Austria', '30 Jun 2024', 'Russell', 7, 71);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Great Britain', '07 Jul 2024', 'Hamilton', 7, 52);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Hungary', '21 Jul 2024', 'Piastri', 6, 70);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Belgium', '28 Jul 2024', 'Hamilton', 7, 44);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Netherlands', '25 Aug 2024', 'Norris', 6, 72);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Italy', '01 Sep 2024', 'Leclerc', 3, 53);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Azerbaijan', '15 Sep 2024', 'Piastri', 6, 51);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Singapore', '22 Sep 2024', 'Norris', 6, 62);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('United States', '20 Oct 2024', 'Leclerc', 3, 56);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Mexico', '27 Oct 2024', 'Sainz', 3, 71);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Brazil', '03 Nov 2024', 'Verstappen', 9, 69);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Las Vegas', '23 Nov 2024', 'Russell', 7, 50);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Qatar', '01 Dec 2024', 'Verstappen', 9, 57);
INSERT INTO races (grand_prix, race_date, winner, team_id, laps) VALUES ('Abu Dhabi', '08 Dec 2024', 'Norris', 6, 58);
