INSERT INTO races (grand_prix, race_date) VALUES ('Bahrain', 'Bahrain');
INSERT INTO races (grand_prix, race_date) VALUES ('Saudi Arabia', '02 Mar 2024');
INSERT INTO races (grand_prix, race_date) VALUES ('Australia', 'Verstappen');
INSERT INTO races (grand_prix, race_date) VALUES ('Japan', 'Red Bull Racing Honda RBPT');
INSERT INTO races (grand_prix, race_date) VALUES ('China', '57');
INSERT INTO races (grand_prix, race_date) VALUES ('Miami', '');
INSERT INTO races (grand_prix, race_date) VALUES ('Emilia-Romagna', 'Saudi Arabia');
INSERT INTO races (grand_prix, race_date) VALUES ('Monaco', '09 Mar 2024');
INSERT INTO races (grand_prix, race_date) VALUES ('Canada', 'Verstappen');
INSERT INTO races (grand_prix, race_date) VALUES ('Spain', 'Red Bull Racing Honda RBPT');
INSERT INTO races (grand_prix, race_date) VALUES ('Austria', '50');
INSERT INTO races (grand_prix, race_date) VALUES ('Great Britain', '');
INSERT INTO races (grand_prix, race_date) VALUES ('Hungary', 'Australia');
INSERT INTO races (grand_prix, race_date) VALUES ('Belgium', '24 Mar 2024');
INSERT INTO races (grand_prix, race_date) VALUES ('Netherlands', 'Sainz');
INSERT INTO races (grand_prix, race_date) VALUES ('Italy', 'Ferrari');
INSERT INTO races (grand_prix, race_date) VALUES ('Azerbaijan', '58');
INSERT INTO races (grand_prix, race_date) VALUES ('Singapore', '');
INSERT INTO races (grand_prix, race_date) VALUES ('United States', 'Japan');
INSERT INTO races (grand_prix, race_date) VALUES ('Mexico', '07 Apr 2024');
INSERT INTO races (grand_prix, race_date) VALUES ('Brazil', 'Verstappen');
INSERT INTO races (grand_prix, race_date) VALUES ('Las Vegas', 'Red Bull Racing Honda RBPT');
INSERT INTO races (grand_prix, race_date) VALUES ('Qatar', '53');
INSERT INTO races (grand_prix, race_date) VALUES ('Abu Dhabi', '');
