INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Bahrain', '02 Mar 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 57);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Saudi Arabia', '09 Mar 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 50);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Australia', '24 Mar 2024', 'Sainz', 'Ferrari', 58);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Japan', '07 Apr 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 53);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('China', '21 Apr 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 56);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Miami', '05 May 2024', 'Norris', 'McLaren Mercedes', 57);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Emilia-Romagna', '19 May 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 63);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Monaco', '26 May 2024', 'Leclerc', 'Ferrari', 78);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Canada', '09 Jun 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 70);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Spain', '23 Jun 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 66);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Austria', '30 Jun 2024', 'Russell', 'Mercedes', 71);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Great Britain', '07 Jul 2024', 'Hamilton', 'Mercedes', 52);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Hungary', '21 Jul 2024', 'Piastri', 'McLaren Mercedes', 70);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Belgium', '28 Jul 2024', 'Hamilton', 'Mercedes', 44);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Netherlands', '25 Aug 2024', 'Norris', 'McLaren Mercedes', 72);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Italy', '01 Sep 2024', 'Leclerc', 'Ferrari', 53);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Azerbaijan', '15 Sep 2024', 'Piastri', 'McLaren Mercedes', 51);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Singapore', '22 Sep 2024', 'Norris', 'McLaren Mercedes', 62);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('United States', '20 Oct 2024', 'Leclerc', 'Ferrari', 56);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Mexico', '27 Oct 2024', 'Sainz', 'Ferrari', 71);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Brazil', '03 Nov 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 69);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Las Vegas', '23 Nov 2024', 'Russell', 'Mercedes', 50);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Qatar', '01 Dec 2024', 'Verstappen', 'Red Bull Racing Honda RBPT', 57);
INSERT INTO races (grand_prix, race_date, winner, car_team_name, laps) VALUES ('Abu Dhabi', '08 Dec 2024', 'Norris', 'McLaren Mercedes', 58);
